// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qupqcibnziwlpnvqjmji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cHFjaWJueml3bHBudnFqbWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODA0MjcsImV4cCI6MjA2MTk1NjQyN30.r0kTxukJM6Do_CObO1fEV9iobO1qQG6-t6ikZTOVDE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);